FROM thbeh/r-base:3.4.2

RUN apt-get update && apt-get install -y supervisor libxml2-dev

COPY packages.R /tmp/
COPY runModel.R /tmp/
COPY scoreDrill.R /tmp/
COPY supervisord.conf /etc/

RUN mkdir /code
ADD code /code

RUN Rscript /tmp/packages.R
RUN R CMD INSTALL /code/returnsModel_2.1-7.tar.gz

EXPOSE 8080
CMD ["supervisord","-c", "/etc/supervisord.conf"]
